name: Build and Push to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nginx-micro-web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        run: |
          docker build -t "$IMAGE:${{ github.sha }}" .

      - name: Tag the image
        run: |
          docker tag "$IMAGE:${{ github.sha }}" "$IMAGE:latest"

      - name: Push the image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push "$IMAGE:latest"

      - name: Success
        run: |
          echo "Job finished."
